version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgres://postgres:YcZHpZJUmkqSef0O8XYOXB3C4AAIuK1UGC4i0Axr5GAOKP4jKDMeXqgkn60oGHQg@192.168.1.50:5432/postgres
    depends_on:
      - frontend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
